In [5]:
a = "0100"
b = 0
for i in a:
    print(i)
    print(b)
    b = (b + << a) + int(i)

SyntaxError: invalid syntax (2365762770.py, line 6)

In [13]:
a = 3
b = a << 1

In [14]:
b

6

In [15]:
print(bin(a))
print(bin(b))

0b11
0b110


In [2]:
a = '1001'

def bin_to_dec(a:str)-> int:
    res = 0
    for i in range(len(a)):
        res = res + int(a[i]) * 2 ** (len(a) - i -1)
    return res

print(bin_to_dec(a))    

9


In [2]:
class A(object):
    def __init__(self) -> None:
        print("do init")
    def __new__(cls):
        print("do new")
        return object.__new__(cls)
A()

do new
do init


In [27]:
import torch
def create_frustum():
    iH, iW = 512, 512
    fH, fW = int(512/8), int(512/8)

    ds = (
        torch.arange(start=1,end=60,step=0.5, dtype=torch.float)
        .view(-1, 1, 1)
        .expand(-1, fH, fW)
    )
    D, _, _ = ds.shape
    print(ds.shape)
    xs = (
        torch.linspace(0, iW - 1, fW, dtype=torch.float)
        .view(1, 1, fW)
        .expand(D, fH, fW)
    )
    print(xs.shape)
    ys = (
        torch.linspace(0, iH - 1, fH, dtype=torch.float)
        .view(1, fH, 1)
        .expand(D, fH, fW)
    )
    print(ys.shape)
    frustum = torch.stack((xs, ys, ds), -1)
    return frustum

In [50]:
a = create_frustum()
print("a", a.shape)
print(a[117,63,63,:])
print(a[0,0,0,:])
print(a[1,0,0,:])
print(a[117,0,0,:])
print('--------------')
print(a[0,1,0,:])
print(a[1,1,0,:])
print(a[117,1,0,:])




torch.Size([118, 64, 64])
torch.Size([118, 64, 64])
torch.Size([118, 64, 64])
a torch.Size([118, 64, 64, 3])
tensor([511.0000, 511.0000,  59.5000])
tensor([0., 0., 1.])
tensor([0.0000, 0.0000, 1.5000])
tensor([ 0.0000,  0.0000, 59.5000])
--------------
tensor([0.0000, 8.1111, 1.0000])
tensor([0.0000, 8.1111, 1.5000])
tensor([ 0.0000,  8.1111, 59.5000])


In [5]:
import torch
a = torch.rand([4, 1, 1, 32768, 4, 4])# ([1, 1, 118, 90, 240, 3, 1])
b = torch.rand([4, 1, 1, 32768, 4, 1])#([1, 1, 118, 90, 240, 3, 3])

c = torch.matmul(a, b)
print(c.shape)

torch.Size([4, 1, 1, 32768, 4, 1])


In [10]:
a = torch.rand([2, 118, 90, 240, 3])
a = a.repeat(2,1,1,1,1,1)
print(a.shape)

torch.Size([2, 2, 118, 90, 240, 3])


In [ ]:
def create_frustum(self):
    iH, iW = self.image_size
    fH, fW = self.feature_size

    ds = (
        torch.arange(*self.dbound, dtype=torch.float)
        .view(-1, 1, 1)
        .expand(-1, fH, fW)
    )
    D, _, _ = ds.shape

    xs = (
        torch.linspace(0, iW - 1, fW, dtype=torch.float)
        .view(1, 1, fW)
        .expand(D, fH, fW)
    )
    ys = (
        torch.linspace(0, iH - 1, fH, dtype=torch.float)
        .view(1, fH, 1)
        .expand(D, fH, fW)
    )


    frustum = torch.stack((xs, ys, ds), -1)
    return frustum